Server: #服务配置
  RunMode: debug # gin的运行模式
  HttpPort: 8000 # http监听端口
  ReadTimeout: 60 # http读取最大时间
  WriteTimeout: 60 # http写入最大时间
App: # 应用配置
  DefaultPageSize: 10 # 默认分页数量
  MaxPageSize: 100 # 最大分页数量
  LogSavePath: storage/logs # 默认应用日志存储地址
  LogFileName: app # 应用日志文件名称
  LogFileExt: .log # 应用日志文件后缀
  # 文件上传部分
  UploadSavePath: storage/uploads # 文件保存目录
  UploadServerUrl: http://127.0.0.1:8000/static # 文件展示地址
  UploadImageMaxSize: 5 # 文件上传允许的大小 MB 
  UploadImageAllowExts: # 文件上传允许的后缀
    - .jpg
    - .png
    - .jpeg
  # 文件上传end
Database: # 数据库配置
  DBType: mysql # 数据库类型
  Username: root # 数据库账号
  Password: 123456 # 数据库密码
  Host: 127.0.0.1:3306 # 数据库地址
  DBName: oms # 数据库名称
  TablePrefix: oms_ # 数据库表前缀
  Charset: utf8 # 数据库编码
  ParseTime: True # time.Time类型自动转换
  MaxIdleConns: 10 # 最大空闲连接数量
  MaxOpenConns: 30 # 最大打开的连接数
JWT: # JWT配置
  Secret: shengwang
  Issuer: oms
  Expire: 7200
Email: # 邮件配置
  Host: smtp.qq.com
  Port: 465
  Username: 793954500@qq.com
  Password: guotao4868262019
  IsSSL: true
  From: 793954500@qq.com
  To:
    - gt793954500@gmail.com